### PR TITLE
M_Jucker_201907

### PR DESCRIPTION
**Pull request by mjucker**
This article describes some of the challenges and culprits of working with a mixed layer ocean and trying to arrive at an acceptable climatology with a minimum number of parameters.
We discuss why even the simplest version of the Model of an idealized Moist Atmosphere [MiMA](https://github.com/mjucker/MiMA) [[Jucker and Gerber (2017)](http://journals.ametsoc.org/doi/10.1175/JCLI-D-17-0127.1)] includes meridional heat flux ("Q-flux"), a meridionally inhomogeneous mixed layer depth, options to reduce the mixed layer depth locally ("land"), as well as options to change surface albedo.

### CODE REVIEW

**Comment by penmaher** [comment]
Hi Martin, I am happy to review. I have taken a fork. Are you happy for me to attach an annotated pdf of your markdown file or would you like a pdf with text comments? The former I could do for smaller comments and the latter if there are any larger comments?

**Comment by mjucker** [comment]
hm. I thought this could be done directly via comments on the pull request. do you need an additional document?

On 2 Aug 2019, 19:29 +1000, Penelope Maher <notifications@github.com>, wrote:

Hi Martin, I am happy to review. I have take taken a fork. Are you happy for me to attached an annotated pdf of your markdown or would you like a pdf of text comments? The former I could so for smaller comments and the latter if there are any larger comments?

**Comment by mjucker** [comment]
oh, this is on github. I’ll reply again on github ;)

—
Dr. Martin Jucker
Lecturer, Climate Change Research Centre
Associate Investigator, Centre of Excellence for Climate Extremes
University of New South Wales
@DrJucker<twitter.com/DrJucker>
www.martinjucker.com<https://www.martinjucker.com>
On 2 Aug 2019, 19:29 +1000, Penelope Maher <notifications@github.com>, wrote:

Hi Martin, I am happy to review. I have take taken a fork. Are you happy for me to attached an annotated pdf of your markdown or would you like a pdf of text comments? The former I could so for smaller comments and the latter if there are any larger comments?

**Comment by penmaher** [comment]
I thought I might need to compile a tex file or similar so I forked without much investigation. I think it will be good to upload comments here. I mostly wanted to find out if annotations on a pdf are acceptable (as they are faster to write for me and faster to action for you).

**Comment by mjucker** [comment]
I think the answer is "whatever works best". It's the philosophy of the entire thing. The pull request workflow is made for adding comments to specific parts of code (or lines of text in this case) and requesting changes, so I thought this is exactly what the review is about. But if you prefer doing it another way, that's fine.

**Comment by penmaher** [comment]
Hi Martin,

Attached are my comments: [MiMA_mixed_layer_maher_review.pdf](https://github.com/research-iceberg/research-iceberg.github.io/files/3481662/MiMA_mixed_layer_maher_review.pdf)

On the whole it looks good. I have no major comments.  Most of my comments are 'minor' or comments for editing. Let me know if anything i have written is not clear.

Penny

**Comment by penmaher** [comment]
As an FYI: I don't work with md very much so I converted the file from md to pdf. Might be worth adding somewhere the following suggestion for how to convert it: 

`pandoc -s MiMA_mixed_layer.md -o MiMA_mixed_layer.pdf`

using [https://pandoc.org/](url)

**Review by penmaher — CHANGES_REQUESTED** [review]
I have added my review notes in the pdf in the comments.

**Comment by penmaher** [comment]
Thanks for the new revision. A couple of things:
1. para before seasonal cycle, suggest replacing the first two sentences with: "The depth of the mixed layer impacts the spin up time of the model: a 100m mixed layer takes 30 years  to converge while a10m mixed layer only 10 years."  These seem very long - the grey scheme only takes about 2 years for a 10m ocean - does it really take 5x longer to stabilise or is 10 years an upper limit to ensure you're using converged data?
 
2. seasonal cycle paragraph 2-3 are the same as para 4 but with different editing. Can you review please?

3. I was thinking that Fig 2 magenta was the diff of the 10m and 100m case but I see how it is the varied mixed layer ocean case. Suggest you say that in caption 2 and change the label to something that is not "10m-100m" maybe 'varied depth'?

4. In the comments section replace 'klick' with "click".

Other than that all good from my perspective.

**Comment by penmaher** [comment]
Excellent idea to include the namelist files and data. Big plus!

You have my sign off. Please feel free to merge in your branch and publish.

**Review by penmaher — APPROVED** [review]
I am happy with the manuscript and the changes. Please proceed.

**Comment by mjucker** [comment]
Accepted contribution. Will now go to editor for final publication.

**Pull request merged**
